### ISSUE TITLE
Change language about wasm-gc

### ISSUE THREAD

**Issue by johnthagen** [rust-lang-nursery/rust-wasm#100]
On this page: https://rust-lang-nursery.github.io/rust-wasm/hello-world.html

```
# make the binary a little smaller (working around bugs in rustc toolchain)
$ wasm-gc target/wasm32-unknown-unknown/release/hello_world.wasm -o hello_world.gc.wasm
```

On macOS using the latest nightly `rustc` and `wasm-gc` this step reduces the size of the `.wasm` file from 649K to 218K. To me that is not "a little smaller". I'd recommend changing the language as I almost skipped this step thinking it would only drop the size by ~10%. Perhaps on larger binaries the difference is not as much?

If there is better language I'd be happy to submit a PR.

**Comment by teovoinea** [comment]
We could probably use the same language used in the [crate](https://github.com/alexcrichton/wasm-gc)?

> Remove all unneeded exports, imports, functions, etc.
