### ISSUE TITLE
WebAssembly Working Group Meeting #3

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-wasm#105]
Continuing our every-other-week meetings, we have another meeting coming up this Thursday, April 5<sup>th</sup>, 2018.

**Doodle for choosing a time:** https://doodle.com/poll/ewi37ptk6qw8pzub

**Add agenda items here:** https://paper.dropbox.com/doc/RustWebAssembly-WG-dcXi5F7Bqlvg10zd7dKve

_(Let's keep re-using this same dropbox paper doc for every meeting so that we don't have to wrangle so many URLs and have an easy way to look back on older minutes.)_

**Comment by mgattozzi** [comment]
@fitzgen do you want me to put last weeks meeting stuff in there as well as summary from last time then?

**Comment by fitzgen** [comment]
> @fitzgen do you want me to put last weeks meeting stuff in there as well as summary from last time then?

I already did :)

**Comment by mgattozzi** [comment]
Awesome :D I hadn't checked since I was breifly skimming issues when I got into work today. Great!

**Comment by fitzgen** [comment]
Ok, looks like the most number of people were available at 9am PDT, so we'll go with that. Talk to y'all tomorrow!

**Comment by fitzgen** [comment]
FYI, we decided to keep the current time slot and meet every two weeks.
