### ISSUE TITLE
Document guidance on optimizing for size

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rust-wasm#109]
Right now there's a lot of home-grown knowledge about how you optimize Rust code for *size* rather than speed, and we should document this! Many use cases of wasm have file size as a very important feature to optimize for, and we want to make sure that everyone can be thoroughly educated on how to make the smallest possible wasm binaries. 

Something like https://jamesmunns.com/update/2018/04/01/tinyrocket.html is a great start but we probably want some wasm-specific instructions, such as:

## Without changing source code

* Compile with LTO 
  
  ```toml
  # in Cargo.toml  
  [profile.release]
  lto = true
  ```

  This is probably the number one thing you can do to reduce your output size. Using LTO works around bugs in today's LLD (to be fixed with an LLD update) but also gives LLVM the most opportunities to internalize, inline, and delete functions. At the same time this also produces the fastest code :)

* Tell LLVM to optimize for size, not speed
  
  ```toml
  # in Cargo.toml  
  [profile.release]
  opt-level = 's' # or 'z'
  ```

* Compile with panic=abort. While this is the default today it may not always be

  ```toml
  # in Cargo.toml  
  [profile.release]
  panic = 'abort'
  ```

* Use the `wasm-opt` tool from the [binaryen toolkit](https://github.com/WebAssembly/binaryen/)

  ```
  wasm-opt -Os -o output.wasm input.wasm
  ```

  LLVM's code generator that we're using isn't quite as mature as `wasm-opt`, so `wasm-opt` can often get some 15-20% size wins purely over what LLVM generates.

* Use the [`wasm-gc`](https://crates.io/crates/wasm-gc) tool. This was greatly needed before the days of LLD but nowadays it will likely only shave off a few bytes rather than produce any significant wins

  ```
  cargo install wasm-gc # only needed once
  wasm-gc foo.wasm
  ```

## Changing source code

* Avoid string formatting. For example `format!`, `to_string`, etc, can bring in a lot of code bloat. If possible only do string formatting in debug mode and in release mode use static strings.
* Avoid panicking. This is definitely easier said than done, but tools like [svelte](https://github.com/fitzgen/svelte/) can help you figure out what functions are panicking.
* Avoid allocation. This is often **very** hard to do, but whenever you allocate in Rust you need to bring a long an allocator to implement that, and that allocator can have a large-ish size footprint.
* Switch allocators. If you must allocate but you don't need it to be fast, then an allocator like [wee_alloc](https://github.com/rustwasm/wee_alloc) is for you.

**Comment by est31** [comment]
cc @rust-lang/wg-codegen

**Comment by fitzgen** [comment]
Thanks for writing this up!

**Comment by mgattozzi** [comment]
@alexcrichton if we put this in the book should we put as is or should we expand it out a bit? Would we also want a section on speed improvements rather than size and talk about where the two overlap?

**Comment by est31** [comment]
cross linking https://github.com/rust-lang-nursery/embedded-wg/issues/69

**Comment by fitzgen** [comment]
As mentioned in yesterday's meeting and notes, I am writing a new draft/tutorial that uses the game of life as a running example, and I plan on having a chapter about code size profiling. Will integrate this stuff there.

**Comment by mgattozzi** [comment]
@fitzgen whenever you get that up just tag me for review!

**Comment by fitzgen** [comment]
#111 merged and I think this can be closed now.
