### ISSUE TITLE
Explain what a glider is in GoL exercise that mentions them

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-wasm#129]
People who are new to the game of life don't necessarily know what a glider is.

**Comment by adityac8** [comment]
I think **glider** is mentioned in `game-of-life/interactivity`. We could give a link to the [Wiki](https://en.wikipedia.org/wiki/Glider_(Conway%27s_Life)) Page. @fitzgen What do you think?

**Comment by fitzgen** [comment]
Sounds good to me!

**Comment by adityac8** [comment]
I'm on it!
