### ISSUE TITLE
GoL: Convert diagram of memory into an image

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-wasm#130]
The diagram of a universe's cells' memory layout in the "Implementing" chapter.

Apparently lots of "monospace" fonts don't render box drawing characters with fixed width.

We should convert this to an image so we know that it looks good on all systems.

**Comment by adityac8** [comment]
This is similar to #131 
I have already created an image for **Example Universe** which could be used in all places having a diagram of universe cells. I'm happy to share the same if that looks great.
![group_1](https://user-images.githubusercontent.com/19192257/39001328-b05df420-4413-11e8-90b5-4952bf5b2423.png)
As this is big in side, we can use `<img>` tag for setting the `width` property for custom sizes.

**Comment by adityac8** [comment]
Hello, @fitzgen Are the suggested changes good to go ?? :nerd_face:

**Comment by fitzgen** [comment]
When I filed this issue, I was thinking of this diagram:

```
Indices:   0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
         ┏━━━┯━━━┯━━━┯━━━┯━━━┯━━━┯━━━┯━━━┯━━━┯━━━┯━━━┯━━━┯━━━┯━━━┯━━━┯━━━┓
  Array: ┃   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   ┃
         ┗━━━┷━━━┷━━━┷━━━┷━━━┷━━━┷━━━┷━━━┷━━━┷━━━┷━━━┷━━━┷━━━┷━━━┷━━━┷━━━┛
   Rows: |     row 0     |     row 1     |     row 2     |     row 3     |
```

I think simply taking a screen shot of it on a system where it is displayed properly, and using that screen shot would work.

The goal is to show how the cells are laid out in linear memory, so a 2D universe misses the point a bit.

**Comment by adityac8** [comment]
I have done that 
![newj 1](https://user-images.githubusercontent.com/19192257/39216040-c6a0ffa2-4837-11e8-912d-0baabd8a42d4.png)
@fitzgen Does this looks good? 😄

**Comment by fitzgen** [comment]
LGTM! Yep, we can remove the style tag too. I think there is another in rules.md, if we didn't already remove it in the last PR.

**Comment by adityac8** [comment]
Okay, @fitzgen I will see to it and make suitable changes followed by PR.
Thank you for the suggestions :smiley:
