### ISSUE TITLE
Example universe in game of life's "Rules" chapter could be more readable

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-wasm#131]
Either switch to image so we know it looks consistent in all browsers/fonts/systems or add spaces between cells or something. One piece of feedback I've received is that it looks funky on some systems right now.

**Comment by adityac8** [comment]
Hello, @fitzgen Is this issue up for solving?

**Comment by fitzgen** [comment]
Yep!

In general, if no one else has commented that they are working on an issue, and there aren't any open PRs for it, you can take the issue. It is polite to leave a comment that you're working on fixing it, so that people who come later don't accidentally duplicate effort. But no need to ask for permission every time, you can just do it :)

**Comment by adityac8** [comment]
I'm on it! 😂
