### ISSUE TITLE
Rust+WebAssembly Working Group Meeting #4

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-wasm#135]
Our next meeting will be this **Thursday, April 19<sup>th</sup> at 16:00 UTC**.

Add agenda items here: https://paper.dropbox.com/doc/RustWebAssembly-WG-dcXi5F7Bqlvg10zd7dKve

**Comment by fitzgen** [comment]
Also, if anyone wants a recurring calendar invite for this meeting, PM me on irc to give me the email address you'd like the invite sent to :)

**Comment by adityac8** [comment]
Hello @fitzgen 
Can new members also attend the meeting?

**Comment by fitzgen** [comment]
Hangouts link for the meeting in 12 minutes: https://hangouts.google.com/call/4Tm7Nn-vbMevnTEI5UCkAAEE

**Comment by fitzgen** [comment]
Thanks everyone!
