### ISSUE TITLE
Rust+WebAssembly Working Group Meeting #5

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-wasm#149]
Our next meeting will be **Thursday, May 3<sup>rd</sup> at 16:00 UTC**.

Add agenda items here: https://paper.dropbox.com/doc/RustWebAssembly-WG-dcXi5F7Bqlvg10zd7dKve

I will post a hangouts link to this thread and on IRC ~15 minutes before we begin.

**Anyone interested in Rust and WebAssembly is invited to join!** Yes, that includes *you!*

**Comment by fitzgen** [comment]
Reminder that this meeting is happening tomorrow! Add your agenda items :)

**Comment by xtuc** [comment]
The time is perfect, i'll join this meeting.

I can answer this question I found in the agenda:

>  Wepback fixes are almost here, anything we can do to help them along?

First any feedback on the approach used would be great. I described the transformation here https://github.com/webpack/webpack/issues/6433#issuecomment-372232238.

Currently we have a blocking issue, i'm working on https://github.com/xtuc/webassemblyjs/tree/master/packages/wasm-edit to improve the robustness of the tool (some binary + transformation are still failling).

**Comment by alexcrichton** [comment]
Oh awesome thanks for the info @xtuc! Looking forward to seeing you soon :)

FWIW I don't think any of LLD/Clang/Rust have the ability to import a global right now. For example this IR:

```ll
@FOO = external global i32

define i32 @foo() {
start:
  %0 = load i32, i32* @FOO, align 4
  ret i32 %0
}
```

generates this final binary:

```
  (type (;0;) (func))
  (type (;1;) (func (result i32)))
  (func $__wasm_call_ctors (type 0))
  (func $foo (type 1) (result i32)
    i32.const 0
    i32.load)
  (table (;0;) 1 1 anyfunc)
  (memory (;0;) 2)
  (global (;0;) (mut i32) (i32.const 66560))
  (global (;1;) i32 (i32.const 66560))
  (global (;2;) i32 (i32.const 1024))
  (export "memory" (memory 0))
  (export "__heap_base" (global 1))
  (export "__data_end" (global 2))
  (export "foo" (func $foo)))
```

In that sense we'd at least be totally workable landing support for the two bugs we have today (not working in chrome and webpack-dev-server caching too aggressively). Once the toolchain has support for importing/exporting globals though I'd love to help out with test cases/fixes where possible!

**Comment by xtuc** [comment]
@alexcrichton something like that https://github.com/WebAssembly/binaryen/pull/1500?

In my free time I'm working on the support in LLVM and Clang. Rust could probably take advantage of it.

**Comment by alexcrichton** [comment]
@xtuc I think that binaryen PR is interpreting the "assembly" (is that even the right name for it?) output of LLVM, right? We don't currently use `s2wasm` from binaryen or the wasm-linker, but rather we use LLVM's native object file format (sort-of wasm binary files) and LLD to link them together. In that sense I think it's different from your PR in that it's primarily adding support for things in binaryen but isn't dealing with LLVM/LLD (which would affect this)

Now it'd be awesome to get this working in LLVM/Clang for sure, this is a definite missing piece of functionality in Rust's wasm support today!

**Comment by xtuc** [comment]
Yes that's correct, my PR only uses the textual LLVM IR output (`.s`) mostly because it's easier to test. I'm planning to add it to `o2wasm` in the future as well.

I haven't looked into the object files for the wasm target yet but we can probably add it to the metadata in order to behave correctly during linking (lld).

**Comment by fitzgen** [comment]
**Hangouts link for this meeting: https://hangouts.google.com/call/vG6rIQOR0lQcHRMgZx5SAAEE**

**Comment by fitzgen** [comment]
Thanks for participating in the meeting, everyone!
