### ISSUE TITLE
Add a warning about webpack/Chrome to the wasm-pack guide in the book

### ISSUE THREAD

**Issue by jasondavies** [rust-lang-nursery/rust-wasm#150]
Basically, following the wasm-pack tutorial and using webpack with Chrome doesn't work due to webpack/webpack#6475.

Chrome has disabled synchronous loading of >4KB wasm binaries in the main thread, in order to encourage their preferred alternative (async) API, so webpack needs to make some changes in order to comply.

I think it might be helpful to add a note to this effect, at least until webpack is fixed: the reader should test in Firefox (or any non-Chrome browser).

**Comment by jasondavies** [comment]
Looks like this has now been fixed in webpack (see linked issue)!

**Comment by xtuc** [comment]
Yes it was fixed in Webpack > 4.8.0
