### ISSUE TITLE
Should wasm-pack generate an index.js in the module?

### ISSUE THREAD

**Issue by mstange** [rust-lang-nursery/rust-wasm#152]
In the wasm-add example, the main JS file in the generated module is `wasm-add/wasm_add.js`. This means that you have to specify the JS filename when importing that module e.g. through webpack.

If the generated JS file were called `index.js` instead, or if its name was declared as the main file using [the `main` property in the module's package.json](https://docs.npmjs.com/files/package.json#main), one would be able to use just `import("wasm-add")` to import the module, which would be a bit nicer.

This would also allow the "test in your browser" button on the npm package site to work more smoothly. For example, if you click that button on [https://www.npmjs.com/package/@mgattozzi/wasm-add](https://www.npmjs.com/package/@mgattozzi/wasm-add), you get to [https://npm.runkit.com/@mgattozzi/wasm-add](https://npm.runkit.com/@mgattozzi/wasm-add), which says:

> `@mgattozzi/wasm-add` lists no main file and has no index.js, so it can't be directly required. If this is a mistake, please let us know. It may however contain internal files that you can require manually

Is there a reasoning behind not using index.js that I'm missing?

**Comment by mstange** [comment]
Oh, I think I filed this issue in the wrong repo.

**Comment by ashleygwilliams** [comment]
hey! @mstange ! if you move this over to the wasm-pack repo i'm happy to address it- i think you've got an interesting point here! thanks :)
