### ISSUE TITLE
Compilation Error on Debug Builds

### ISSUE THREAD

**Issue by CryZe** [rust-lang-nursery/rust-wasm#168]
I'm still getting compilation errors when compiling in debug mode with the latest nightly:
```
   ...
   Compiling parking_lot v0.5.5
LLVM ERROR: out of memory
error: Could not compile `num-rational`.
```
This happens consistently on multiple PCs. Release Builds work just fine.

To reproduce build the [livesplit-core](https://github.com/LiveSplit/livesplit-core) crate with `cargo build -p cdylib --target wasm32-unknown-unknown`

**Comment by mgattozzi** [comment]
cc/ @alexcrichton

**Comment by alexcrichton** [comment]
This looks like an LLVM issue, which is a bit more clear to identify if LLVM with assertions enabled is used -- 

```
UNREACHABLE executed at /checkout/src/llvm/lib/Target/WebAssembly/WebAssemblyCFGStackify.cpp:252!
```

I'll work on minimizing this and submitting a bug to upstream LLVM

**Comment by alexcrichton** [comment]
This may have been fixed by https://bugs.llvm.org/show_bug.cgi?id=36564 which we haven't cherry-picked yet, testing now

**Comment by alexcrichton** [comment]
Ok confirmed to be fix by that, I'll go do the backport now.

**Comment by alexcrichton** [comment]
https://github.com/rust-lang/rust/pull/50514

**Comment by alexcrichton** [comment]
Confirmed fixed on nightly!

**Comment by CryZe** [comment]
Thank you guys :D
