### ISSUE TITLE
Idea for New logo:Rust Wasm

### ISSUE THREAD

**Issue by adityac8** [rust-lang-nursery/rust-wasm#171]
Tried a new logo for Rust Wasm. Any thoughts on this one?

![wasm-logo 1](https://user-images.githubusercontent.com/19192257/39775333-2cbe397e-531b-11e8-9bd0-fefc1526a174.png)

**Comment by CryZe** [comment]
I'd just take the official WebAssembly Logo and put it in the cogwheel tbh.

**Comment by lukewagner** [comment]
Given that JS is also an integral part of Rust+wasm, it'd be neat to find a way to synthesize the JS+WA logo (on the RHS of [this](https://github.com/WebAssembly/web-assembly-logo/blob/master/dist/presentation.png)) with the cogwheel.

**Comment by CryZe** [comment]
I just made this:

![https://i.imgur.com/gkBg127.png](https://i.imgur.com/gkBg127.png)

**Comment by ashleygwilliams** [comment]
hey all! really love all the creative energy here- wanted to just quickly mention that i think we actually already agreed on a logo (seen here: https://twitter.com/rustwasm). i believe it was decided on in the last rust-wasm meeting, @fitzgen can u confirm?

**Comment by fitzgen** [comment]
My understanding was that we came to the conclusion that the logo we are currently using on the twitter account was Good Enough.

If folks hate the current logo (was not my impression based on the meeting) and love one of these logos, then we can vote on whether to switch or something, but I don't think it is really worth spending much time on it.

**Comment by mgattozzi** [comment]
Yeah I thought we had settled on this during the last meeting. I thought it was fine as is

**Comment by CryZe** [comment]
Well I couldn't make it, so I wasn't there ¯\\\_(ツ)\_/¯

**Comment by adityac8** [comment]
Thank you for the reviews and sorry if caused any inconvenience as I read the meeting agenda before the meeting and thought of presenting it but was not able to do that. 
I liked the way everyone so actively participated in the discussion. 
Thank you :smiley: 
Should I close the issue if the decision is final?

**Comment by fitzgen** [comment]
I think we can close this now, everyone seems fine with the current logo.
