### ISSUE TITLE
Linking to C static library

### ISSUE THREAD

**Issue by wehlutyk** [rust-lang-nursery/rust-wasm#179]
First of all thank you for all the work going into Rust+Wasm, this is super exciting!

Second of all, I'd like to emphasize I'm no expert in any of the tools used here, so if this issue starts to look more like a StackOverflow question please redirect me!

---

I'm trying to lay out the steps needed to progress from a wasm project written in pure Rust, all the way to a Rust project which links in full-fledged C libraries, themselves needing libc, and always using the `wasm32-unknown-unknown` target. Sort of the incremental steps involved in making a hello world version of [alexcrichton/wasm-sodium](https://github.com/alexcrichton/wasm-sodium), with minimal changes at each step, and minimal options for each compilation command. The whole thing could eventually be suitable for a tutorial of sorts (and given that wasm-sodium compiles and runs on my system, in spite of [LLVM warning that the ".o" format is not stable](http://llvm.org/svn/llvm-project/llvm/trunk/lib/Target/WebAssembly/README.txt), I'm assuming this is not premature).

The progression would be:
1. pure Rust → wasm
2. Rust + C lib not using libc → x86_64 (so as to model the next step on this one)
3. Rust + C lib not using libc → wasm
4. Rust + C lib using libc, with stubbed out symbols (a la wasm-sodium) → wasm
5. Rust + C lib using libc, linking to musl → wasm

With maybe a few more intermediary steps around 4 and 5. The code is at [wehlutyk/wasm-explorations](https://github.com/wehlutyk/wasm-explorations), and my issue is with step 3.

Step 3 basically follows wasm-sodium:
* it uses a [docker image](https://github.com/wehlutyk/wasm-explorations/blob/master/3-rust-c-lib-simple/foo/Dockerfile) (extracted from wasm-sodium) to build clang with WebAssembly support (yes, musl is not necessary in that image, but will be useful for later steps)
* [builds `bar.o`](https://github.com/wehlutyk/wasm-explorations/blob/master/3-rust-c-lib-simple/foo/Makefile#L12) in docker then [creates a `libbar.a`](https://github.com/wehlutyk/wasm-explorations/blob/master/3-rust-c-lib-simple/foo/Makefile#L9) archive
* statically [links `libbar.a`](https://github.com/wehlutyk/wasm-explorations/blob/master/3-rust-c-lib-simple/foo/build.rs) in the cargo build

On my system, `make` runs and finishes successfully. However, `npm run serve` fails:
```bash
$ npm run serve

> @ serve /home/sl/Code/Infuse/wasm-explorations/3-rust-c-lib-simple/foo
> webpack-dev-server

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
✖ ｢wdm｣: Hash: de14ae07ce6670079549
Version: webpack 4.8.3
Time: 457ms
Built at: 22/05/2018 13:34:19
                           Asset          Size  Chunks             Chunk Names
                        index.js       344 KiB    main  [emitted]  main
                      0.index.js       8.5 KiB       0  [emitted]  
6d6a479413f6176795f1.module.wasm  unknown size       0  [emitted]  
                      1.index.js      24.2 KiB       1  [emitted]  
Entrypoint main = index.js
[./foo.js] 4.2 KiB {0} [built]
[./index.js] 71 bytes {main} [built]
[./node_modules/ansi-html/index.js] 4.16 KiB {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/node-libs-browser/node_modules/punycode/punycode.js] 14.3 KiB {main} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {main} [built]
[./node_modules/url/url.js] 22.8 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 7.75 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} [built]
[0] multi (webpack)-dev-server/client?http://localhost:8080 ./index.js 40 bytes {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {main} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.03 KiB {main} [optional] [built]
    + 17 hidden modules

ERROR in ./foo_bg.wasm
Module not found: Error: Can't resolve 'env' in '/home/sl/Code/Infuse/wasm-explorations/3-rust-c-lib-simple/foo'
 @ ./foo_bg.wasm
 @ ./foo.js
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./index.js
ℹ ｢wdm｣: Failed to compile.
```

And indeed, `wasm-nm` tells me that `add` (from `libbar`) has not been included in the wasm binary:
```bash
$ wasm-nm foo_bg.wasm
i __wbg_f_log_log_n
i add
i __wbindgen_throw
p foo::log::h0df8ab0bf3fde97c
p foo::greet::h610efd752f2f9b33
p greet
p core::ptr::drop_in_place::h3c1264367c8cbfbf
p core::ptr::drop_in_place::hf72941811ad24805
e greet
< ... many more symbols ... >
```

and it wants to be imported through `env`:
```bash
$ wasm-objdump -x foo_bg.wasm
0032152: warning: invalid linking metadata version: 3

foo_bg.wasm:    file format wasm 0x1

Section Details:

Type:
 - type[0] () -> nil
 - type[1] (i32) -> nil
 - type[2] (i32, i32) -> nil
 - type[3] () -> i32
 - type[4] (i32, i32, i32, i32, i32) -> nil
 - type[5] (i32, i32) -> i32
 - type[6] (i32, i32, i32) -> nil
 - type[7] (i32, i32, i32, i32, i32, i32, i32) -> nil
 - type[8] (i32) -> i32
 - type[9] (i32, i32, i32) -> i32
 - type[10] (i32, i32, i32, i32) -> i32
 - type[11] (i32, i32, i32, i32, i32) -> i32
 - type[12] (i32, i32, i32, i32) -> nil
 - type[13] (i32) -> i64
 - type[14] (i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) -> nil
 - type[15] (i32, i32, i32, i32, i32, i32) -> i32
 - type[16] (i32, i32, i32, i32, i32, i32, i32) -> i32
Import:
 - func[0] sig=2 <__wbg_f_log_log_n> <- ./foo.__wbg_f_log_log_n
 - func[1] sig=5 <add> <- env.add
 - func[2] sig=2 <__wbindgen_throw> <- ./foo.__wbindgen_throw
Function:
 - func[3] sig=2 <foo::log::h0df8ab0bf3fde97c>
 - func[4] sig=2 <foo::greet::h610efd752f2f9b33>
 - func[5] sig=2 <greet>
< ... many more functions ...>
```

Now I'm puzzled as to what wasm-sodium does differently, because `wasm-nm` shows that in that case the external C symbols are included in the wasm binary (assuming I'm reading its output correctly). Is this an issue any of you have run into? Something obvious (or non-obvious) that I'm missing?

I'm guessing something's wrong with the creation of the `libbar.a` archive, since:
```bash
$ wasm-nm libbar/bar.o
i __linear_memory
i __indirect_function_table
i __stack_pointer
e add
```
is fine, but:
```bash
$ wasm-nm libbar/libbar.a 
error: libbar/libbar.a: Invalid magic number at start of file
```

---

EDIT: added reference to [LLVM WebAssembly target notes](http://llvm.org/svn/llvm-project/llvm/trunk/lib/Target/WebAssembly/README.txt)

EDIT 2: add thanks and refer to `wasm32-unknown-unknown` target

**Comment by alexcrichton** [comment]
This is very curious! A lot of this is sort of unexplored territory so I'm not altogether surprised that there's some caveats along the way.

I believe what's happening is that `libbar.a` doesn't have a valid symbol table. The `ar` tool used to assemble the archive doesn't have wasm support (it's just `/usr/bin/ar`). Linkers typically rely on the symbol table to tell them what objects to pull in, and in this case LLD is seeing what's probably a corrupt or empty symbol table so it doesn't actually look inside the archive for the file.

If I change your `ar` step to run inside the docker container and execute `/clang/bin/llvm-ar` instead then it looks to link correctly and `add` is linked in (not imported from the `env`). 

Now that I see this I have no idea how wasm-sodium works. It certainly doesn't go out of its way to "fix" archives...

**Comment by wehlutyk** [comment]
> If I change your `ar` step to run inside the docker container and execute `/clang/bin/llvm-ar` instead then it looks to link correctly and `add` is linked in (not imported from the `env`).

Thanks, that works! I thought I had tried it, but obviously not.

Was it expected that LLD doesn't complain about undefined symbols? (Or is that just because things are not well defined yet?)

> Now that I see this I have no idea how wasm-sodium works. It certainly doesn't go out of its way to "fix" archives...

Browsing libsodium and commits, I'm getting that it relies a lot on Emscripten for its wasm and asm.js build, which might explain why it works, but you might know better. Might get around to it after step 5 :).

Final note: I'm still getting an `Invalid magic number at start of file` for `wasm-nm libbar/libbar.a`, though that might be a wasm-nm question.

This is solved and can be closed from my point of view, thanks again!

**Comment by alexcrichton** [comment]
> Was it expected that LLD doesn't complain about undefined symbols?

This [may or may not](https://github.com/rust-lang/rust/blob/1977849257436cf74a3bbee94ca2860896853b81/src/librustc_codegen_llvm/back/linker.rs#L1015-L1020) be a bug in rustc right now. Currently it's not clear how to classify symbols under "please resolve this from other linked objects" versus "please resolve this from the browser or ambient environment". In that sense it's expected that undefined symbols are allowed, but we'll almost for sure want to tweak this before "stabilization"

> : I'm still getting an Invalid magic number at start of file for wasm-nm libbar/libbar.a, though that might be a wasm-nm question.

I don't know much about wasm-nm but I'd imagine that this is because it's expecting a raw wasm file as input, and not an archive.

**Comment by wehlutyk** [comment]
I'm starting to see how this works. Closing as the original question is solved :) (though more things will crop up undoubtedly).
