### ISSUE TITLE
[question] why is my wasm huge?

### ISSUE THREAD

**Issue by trsh** [rust-lang-nursery/rust-wasm#190]
This is the wasm from demo -> https://www.hellorust.com/demos/add/add.wasm
And this is mine
[hello_world.gc.zip](https://github.com/rust-lang-nursery/rust-wasm/files/2076627/hello_world.gc.zip)

It's like x100. I fallowed all beginner steps from book with --release flag.

**Comment by Hywan** [comment]
Did you run [`wasm-opt`](https://github.com/WebAssembly/binaryen) and maybe [`wasm-snip`](https://github.com/rustwasm/wasm-snip) to reduce its size?

**Comment by trsh** [comment]
@Hywan #![no_std] helped a lot. :)

**Comment by fitzgen** [comment]
Also, be sure to read the "shrinking `.wasm` size" chapter of the book: https://rust-lang-nursery.github.io/rust-wasm/game-of-life/code-size.html

And you can also use Twiggy to size profile your `.wasm` binaries: https://github.com/rustwasm/twiggy

**Comment by trsh** [comment]
@fitzgen tnx. And yes I did shrinking part. Could not miss it from the book :)
