### ISSUE TITLE
Support `lld` on pure wasm backend

### ISSUE THREAD

**Issue by aturon** [rust-lang-nursery/rust-wasm#2]
Currently we avoid the need for *any* linked on `wasm32-unknown-unknown`, by combining all Rust code into a single compilation unit. This allows us to work around the immaturity of the `lld` story for wasm, but at the cost of compile times. This issue tracks the status of the `lld` readiness and rustc's ability to use it.

**Comment by alexcrichton** [comment]
Awhile back I filed https://bugs.llvm.org/show_bug.cgi?id=35369 with at least one cause of "we can't use lld vanilla upstream". There's a whole lot more issues to solve here, but that's at least one concrete actionable one :)

**Comment by pepyakin** [comment]
JFYI Experimental LLD support has been landed in Emscripten

https://github.com/WebAssembly/binaryen/pull/1346
https://github.com/kripken/emscripten/pull/6056

**Comment by alexcrichton** [comment]
I've tested on top of the LLVM 6 upgrade (plus a bit farther on LLVM for a few more patches) with LLD master and everything looks to be working beautifully! Once https://reviews.llvm.org/D42511 lands we won't even need wasm-gc any more, yay!

**Comment by alexcrichton** [comment]
Ok I've now completed a test run of our entire test suite using LLD to link wasm binaries together. Specifically I was using llvm-mirror/lld@95a9b67aa0326d28dfed43df09451677f5f070f2 with https://reviews.llvm.org/D42511 applied manually (but that probably wasn't necessary), llvm-mirror/llvm@d14b8f63313dfa6dfe83c6501140bc17eed0c8a7, and https://github.com/alexcrichton/rust/commit/106657e0fbfffe70c6894e4d1e590d9ffbac5cd5. 

I believe the sequence of steps here are now:

* Wait for LLVM 6 - https://github.com/rust-lang/rust/pull/47828
* Add lld as a submodule (turned off by default) in the rust-lang/rust repository.
* Add build system support to build LLD and make its binary available to rustc to run
* Probably upgrade LLVM again (but a much smaller one) necessary to get LLD building
* Land something along the lines of https://github.com/alexcrichton/rust/commit/106657e0fbfffe70c6894e4d1e590d9ffbac5cd5 in rustc to switch wasm's default linker.

I'd hope we can just switch the defaults overnight and not worry about maintaining the old "LTO everything" link mode. There'll proably be bugs but likely nothing that's too hard to backport!

**Comment by alexcrichton** [comment]
Ok I got a little excited and I've now implemented all of this -- https://github.com/alexcrichton/rust/commit/cbf406f4222dfce6755ccbef48382f637cb39a8b

Once LLVM 6 lands I'll send that as a PR and we should be able to switch to LLD pronto.

**Comment by alexcrichton** [comment]
[PR for this](https://github.com/rust-lang/rust/pull/48125)

**Comment by alexcrichton** [comment]
Landed!

**Comment by alexcrichton** [comment]
FWIW as a testament to the improvements brought about by LLD related to build times, the `wasm32-unknown-unknown` builder we have in rust-lang/rust reduced from [1h53m](https://travis-ci.org/rust-lang/rust/jobs/348802418) per build to [1h10m] per build when this landed, a huge reduction in our build times!

**Comment by mgattozzi** [comment]
Wow that's a huge reduction. Shaving 40+ minutes off is not a trivial gain at all.
