### ISSUE TITLE
Upgrade rustc's LLVM

### ISSUE THREAD

**Issue by aturon** [rust-lang-nursery/rust-wasm#3]
Right now, rustc's LLVM version is coupled to the one used in emscripten, which is perpetually behind. Since LLVM's direct wasm support is under ongoing development, we'd like to get much closer to the tip. To do this, we will likely need to support *multiple* LLVM back-ends for Rust.

**Comment by aturon** [comment]
@alexcrichton, do you want to sketch out the plan here as you currently see it?

**Comment by alexcrichton** [comment]
Certainly, yeah.

The naive thing here is to just [upgrade LLVM](https://github.com/rust-lang/rust/issues/43370). Unfortuantely though the fact that Emscripten hasn't upgraded means that we're still held back and have to consider other options.

The next course of action we have available to us would be https://github.com/rust-lang/rust/issues/46819, namely allowing Emscripten to have it's own custom LLVM backend, allowing the rest of the targets of rustc to upgrade LLVM.

So for now at least I believe the plan is:

* Implement https://github.com/rust-lang/rust/issues/46819
* Get Emscripten on its own custom LLVM backend
* Upgrade the main Rust LLVM to 5.0 (https://github.com/rust-lang/rust/issues/43370)
* Probably upgrade LLVM again to 6.0+ (or whatever master is right now)
  * If it's too onerous we can always make a *wasm* specific LLVM backend so Emscripten is at 4.0, rustc is mostly at 5.0, and everything else is 6.0. That's a huge number of LLVM's though and our CI may not be able to cope with it.

**Comment by alexcrichton** [comment]
The deed is done.
