### ISSUE TITLE
Support for emitting custom sections

### ISSUE THREAD

**Issue by koute** [rust-lang-nursery/rust-wasm#30]
There should be a way to emit [custom wasm sections](https://github.com/sunfishcode/wasm-reference-manual/blob/master/WebAssembly.md#custom-sections) from inside Rust code.

There are many potential uses for custom sections. For example, currently the [the `js!` macro](https://docs.rs/stdweb/0.3.0/stdweb/macro.js.html) in `stdweb` takes JavaScript code, stringifies it, and assigns it to a normal constant. Then [`cargo-web`](https://github.com/koute/cargo-web/) scans the `.wasm` file, extracts those JavaScript snippets, and deletes the (now useless) corresponding data section entries.

Ideally instead of mucking around with the data section (which often creates holes in memory at runtime since you can't really move the entries' offsets around, and is harder to process) it'd just read a custom section which `stdweb` would emit for it, and then easily nuke it afterwards.

One potential way we could support custom sections would be like this: have a built-in macro, say, `append_to_custom_section!`, which would take two arguments: (1) a string with the name of the section, (2) a blob of bytes it would append to that section. It would also be a purely compile-time construct and would expand into nothing after macro expansion.

For example this Rust code:

```rust
append_to_custom_section!("js-snippets", b"\x12\x00\x00\x00console.log('...')")
append_to_custom_section!("js-snippets", b"\x0c\x00\x00\x00alert('...')")
```
would result in a custom wasm section with the name `js-snippets` containing `\x12\x00\x00\x00console.log('...')\x0c\x00\x00\x00alert('...')`. The blobs of bytes would be concatenated in the order of their appearance within one `.rs` file, and with an unspecified order between different `.rs` files.

This would allow a procedural macro to put arbitrary information in a custom section of its choice, which then could be easily consumed by external tools.

**Comment by pepyakin** [comment]
I doubt that LLVM can emit custom sections. Maybe @sunfishcode knows better.

**Comment by sunfishcode** [comment]
It can't currently. It would be possible to add ways to do it. Another option would be to have rustc just append custom sections to the output wasm files itself after LLVM is done.

**Comment by pepyakin** [comment]
Ah, I completly forgot about it is so easy to just slap a section to a wasm file. I actually like this approach!

**Comment by Diggsey** [comment]
Sounds good!

**Comment by sunfishcode** [comment]
There's a patch for this in review upstream: https://reviews.llvm.org/D43097

**Comment by alexcrichton** [comment]
While we wait for support in LLVM/LLD (it'd take us awhile to update LLVM as well) I've opened https://github.com/rust-lang/rust/pull/48883 to implement this

**Comment by alexcrichton** [comment]
This is now in nightly!

**Comment by IAIAE** [comment]
can rust code "read" the custom section in which the wasm file build by itself? @koute
