### ISSUE TITLE
What tier of support is wasm32-unknown-unknown?

### ISSUE THREAD

**Issue by mgattozzi** [rust-lang-nursery/rust-wasm#32]
Over on the [forge](https://github.com/rust-lang-nursery/rust-forge/pull/118) there was a question as to whether this target would be added as Tier 2. Given the description of it, it seems reasonable that it is:

> Tier 2 platforms can be thought of as “guaranteed to build”. Automated tests are not run so it’s not guaranteed to produce a working build, but platforms often work to quite a good degree and patches are always welcome! Specifically, these platforms are required to have each of the following:
    Official binary releases are provided for the platform.
    Automated building is set up, but may not be running tests.
    Landing changes to the rust-lang/rust repository’s master branch is gated on platforms building. For some platforms only the standard library is compiled, but for others rustc and cargo are too.

I'm unsure as to what is or is not true about this list.

**Comment by alexcrichton** [comment]
My personal feeling is that despite providing builds it still feels like "tier 3" because of the instability of the target. Over time though once the dust settles around the integration story I think we could easily become a tier 2 target and perhaps 1 in time.

**Comment by Diggsey** [comment]
Yes, saying it's "tier 2" would be false-advertising right now:
- Binary wasm files are unusable without performing additional transformations.
- Debug builds are broken entirely.
- Linking is not really supported, other than to perform a single giant link step
- Unused sections are not cleaned up without also running wasm-gc.
- Unresolved symbols are only caught at runtime.
- Only panic=abort is supported.
- Libstd is entirely stubbed out to do nothing.
etc. etc.

**Comment by mgattozzi** [comment]
That sounds reasonable to me. Do we have anything written out on the rustc issue tracker that contains a plan of some sort to get it from Tier 3 to Tier 2? Like tasks and goals that need to be accomplished, things that are still stubbed etc? If not I'd be willing to help write that out and plan it so we can keep track of what still needs to be done.

**Comment by alexcrichton** [comment]
Nah not really unfortunately. While we have relatively strict tier definitions they're not necesarily the best definitions (we've long wanted to change them). In that sense we don't have great definitions for what actually is Tier 2 or whatnot, so it's mostly a gut feeling. It's probably best to just track high-priority bugs and fix those.

**Comment by mgattozzi** [comment]
Hmmmm... We might want to make an RFC to change tier definitions then at some point but that's tangential to this. I'll have to take a look through the issue tracker then and create an issue to coallate wasm based issues and help prioritize them as well as areas that are underdeveloped and still need more work.

**Comment by mgattozzi** [comment]
Hmmmm... We might want to make an RFC to change tier definitions then at some point but that's tangential to this. I'll have to take a look through the issue tracker then and create an issue to coallate wasm based issues and help prioritize them as well as areas that are underdeveloped and still need more work. This should make it easier to help users contribute to rustc if they know what's still open.

**Comment by alexcrichton** [comment]
I think this has been effectively answered for the time being as "tier 2" but it effectively continues to move up "tiers" as we continue to pour effort into it!
