### ISSUE TITLE
using sqrt doesn't work as expected

### ISSUE THREAD

**Issue by thekemkid** [rust-lang-nursery/rust-wasm#69]
I've compiled the below code to `wasm-unknown-unknown`. when I call `sqrt(9)` from js I get 0 as the answer. Is there something I don't understand going on in the background?

```
#[no_mangle]
pub extern fn sqrt(n: i32) -> i32 {
  return (n as f32).sqrt() as i32
}
```

I'm happy to setup a small repo for repro if wanted! Thanks :D

**Comment by mgattozzi** [comment]
Just a quick question is this with release mode? Debug is known to not output the right values for things.

**Comment by thekemkid** [comment]
Yup, using `cargo +nightly build --target wasm32-unknown-unknown --release`

**Comment by thekemkid** [comment]
When I wrote a repo for reproducing, it started working. yay phantom issues... I spent far too long debugging this! haha

**Comment by koute** [comment]
This is a total shot in the dark, but are you by any chance using incremental compilation? In the past I've found that compiling with `CARGO_INCREMENTAL=1` produced similar-ish issues.

Also, if you still have the original `.wasm` file on which this reproduces it'd be useful to run it through `wasm2wat` and manually inspect it for anything funky.

**Comment by thekemkid** [comment]
I'm using a standard cargo install, I think that incremental compiling is on. I did a `wasm2wat` on it, but I think I been deleted it after everything started working 😞
