### ISSUE TITLE
Rustc should emit name section for function names

### ISSUE THREAD

**Issue by edre** [rust-lang-nursery/rust-wasm#70]
Webassembly supports a special custom section called "name" to assign names to functions and locals to aid in runtime debugging. For example, the stack traces I get in chrome should have my actual function names instead of random ids. LLVM seems to have support for this, but there is no name section emitted from rustc in either debug or release mode.

https://play.rust-lang.org/?gist=61eee1e3c108ca6db8adf709897feacc&version=nightly

**Comment by fitzgen** [comment]
It does if you enable debugging symbols:

```toml
[profile.release]
debug = true
```

**Comment by fitzgen** [comment]
All of debug builds are semi-broken with wasm at the moment. I don't recommend using them.

**Comment by edre** [comment]
In a future where debug builds are not broken, they're supposed to come with debugging symbols, right?

**Comment by fitzgen** [comment]
Yeah, I think so.

**Comment by edre** [comment]
This issue probably doesn't need to be tracked separately then.
