### ISSUE TITLE
Schedule a meeting for the Rust+WASM domain working group

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-wasm#77]
**Time sensitive!**

Trying to schedule a time that would work for folks interested in the rust+wasm WG. Unclear if this will be recurring and if so at what frequency. Want to just get as many folks together as we can at least once at the start to get a sense of where we are.

~~Check off the boxes when you are available, if you're interested in attending: https://doodle.com/poll/eq3ymua89rpf9ckw~~

------------------

EDIT:

**The meeting will be this Thursday at 11am pacific ([19:00 UTC](https://www.worldtimebuddy.com/?qm=1&lid=8,100,2643743&h=8&date=2018-3-8&sln=11-12))**

I'll post a hangouts link in #rust-wasm IRC for us all to join at that time.

If you have something you'd like to bring up, please add it to the agenda: https://paper.dropbox.com/doc/RustWebAssembly-WG-dcXi5F7Bqlvg10zd7dKve

**Comment by Pauan** [comment]
How will the meeting be conducted? Skype?

**Comment by mgattozzi** [comment]
I would assume IRC like most other open rust meetings. #rust-wasm channel most likely

**Comment by fitzgen** [comment]
> How will the meeting be conducted? Skype?

I've had success with hangouts.

appear.in is also great, but has a limit of four participants unless you pay, so I don't think it is an option here.

> I would assume IRC like most other open rust meetings. #rust-wasm channel most likely

I'd actually prefer to do video chat, at least at first, since it is higher bandwidth.

**Comment by Pauan** [comment]
> I'd actually prefer to do video chat, at least at first, since it is higher bandwidth.

As long as it also has an option for text chat: not everybody has a webcam/microphone (I don't).

**Comment by fitzgen** [comment]
Hangouts does have text chat.

**Comment by mgattozzi** [comment]
That works for me.

**Comment by sendilkumarn** [comment]
Hangouts work for me too 👍

**Comment by fitzgen** [comment]
Thanks for filling out the doodle, everyone!

**The meeting will be this Thursday at 11am pacific ([19:00 UTC](https://www.worldtimebuddy.com/?qm=1&lid=8,100,2643743&h=8&date=2018-3-8&sln=11-12))**

I'll post a hangouts link in #rust-wasm IRC for us all to join at that time.

If you have something you'd like to bring up, please add it to the agenda: https://paper.dropbox.com/doc/RustWebAssembly-WG-dcXi5F7Bqlvg10zd7dKve

**Comment by mgattozzi** [comment]
Yay good team meeting! I'll open up an issue for the next meeting so we can do a doodle and schedule it two weeks from now :D
