### ISSUE TITLE
Accessing wasm globals

### ISSUE THREAD

**Issue by wanderer** [rust-lang-nursery/rust-wasm#98]
I need to be able to access a wasm global `get_global`. Is there anyway to do this?

**Comment by alexcrichton** [comment]
Thanks for the report! Can you explain a bit more about your use case? Are you trying to access a static somewhere else or export a static?

**Comment by wanderer** [comment]
in our usecase the globals are set by the host environment to indicate various settings

**Comment by pepyakin** [comment]
You can import it with `extern` block just as ordinary function;

```rust
extern {
    static X: u32;
}
```

will yield such import in wasm

```WebAssembly
(import "env" "X" (global i32))
```

**Comment by alexcrichton** [comment]
Indeed I think that should do the trick!

**Comment by alexcrichton** [comment]
(although let me know if that doesn't work!)
